environment:
  PROJECT_NAME: FreenetInstaller
  VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CONFIGURATION: Release
  ARCH: x64

install:
  - if defined VS call "%VS%" %ARCH%
  - choco install -y innosetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - iscc "Ghostly Skills.iss" /DPWD=%CD% /OOutput

before_deploy:
  - cd Output
  - copy /y %PROJECT_NAME%.exe %PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%.exe
  - appveyor PushArtifact %PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%.exe

deploy:
  description: 'Ghostly-Skills_Setup'
  artifact: /.*\.exe/
  #  To change this token:
  #
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the `public_repo` scope enabled
  # - Go to 'https://ci.appveyor.com/tools/encrypt', log in, and paste the token
  # - Replace the "value" below
  auth_token:
    secure: XGgQhf14TFBYXGacZtr4WkUcMD5d8FdSaxb9Vp6SZnof0rVFTQDBDA/MqSA2PHqi
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - Windows-OS
    - fix-64
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/
