name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout fred
      uses: actions/checkout@v2
      with:
        repository: 'freenet/fred'
        fetch-depth: 0
        path: 'fred'

    - name: Download fred from the Github Release
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: "freenet"
        repo: "fred"
        tag: "latest"
        file: "freenet.jar"

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: updateSetupFile
        
    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Ghostly Skills.iss"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "Output/Ghostly-Skills_Setup.exe"
        name: wininstaller-innosetup

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      
    - name: Configuring the default profile
      run: git config --global user.name "Minionguyjpro"

    - name: Adding all the files
      run: git add .
      
    - name: Commiting the changes
      run: git commit -am "Build new version of the installer"
      
    - name: Pushing to Repo
      run: git push origin Windows-OS
