# Give the workflow a name. 
name: Nightly Build

# Trigger Workflow every midnight UTC

on:
  push:
    branches:
      - Android-OS
  pull_request:
    branches:
      - Android-OS
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch: 
#workflow_dispatch helps run workflow anytime with a single click. 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Scheduling
    # make sure to run this action in Linux env (say ubuntu)
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build
